### ISSUE TITLE
Getting Uncaught Error: Unauthorized when running tests

### ISSUE THREAD

**Issue by FutoRicky** [mainmatter/ember-cli-simple-auth-testing#12]
I followed the ReadMe instructions but I am still unable to initiate session when running tests. This is the error I am getting: 
`Uncaught Error: Unauthorized at http://localhost:7357/assets/vendor.js, line 35918`

**Comment by marcoow** [comment]
Please provide more info - test source, network requests etc.

**Comment by FutoRicky** [comment]
Using ember-qunit, network requests are simple ajax calls. 

this is an example of the console errors:
`GET http://readcoach.herokuapp.com/profile 401 (Unauthorized)`
`Uncaught Error: Unauthorized`

**Comment by marcoow** [comment]
So you're receiving a 401 response from sth. somewhere in your code. If you think that's bug in ESA please provide some basic info (config, test code etc.) so that people can actually help you.
